name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: update go.mod
        run: cd src && go mod tidy
      - name: Create config file
        run: |
          mkdir ~/.config/egolottery
          touch ~/.config/egolottery/config.yaml
          echo directories:  >> ~/.config/egolottery/config.yaml
          echo "  - \"$PWD\"" >> ~/.config/egolottery/config.yaml
          echo group: \"days\" >> ~/.config/egolottery/config.yaml
          echo timeago: 150 >> ~/.config/egolottery/config.yaml
          echo searchdepth: 0 >> ~/.config/egolottery/config.yaml
          echo emails: >> ~/.config/egolottery/config.yaml
          echo \ \ - \"augustbrandt170@gmail.com\" >> ~/.config/egolottery/config.yaml
          echo \ \ - \"aubr@itu.dk\" >> ~/.config/egolottery/config.yaml
      - name: Unit tests
        run: cd src && go test ./...