name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: update go.mod
        run: cd src && go mod tidy
      - name: Unit tests
        run: cd src && go test
      - name: end to end test
        run: cd test && go test